version: '3.8'

services:

  mongodb:
    image: mongo:7.0
    container_name: pppk-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: bird_pipeline
    volumes:
      - /mnt/hdd-storage/PPPK/mongodb_data:/data/db
    networks:
      - pipeline-network


  minio:
    image: minio/minio:latest
    container_name: pppk-minio
    restart: unless-stopped
    ports:
      - "9110:9000"   # API port
      - "9111:9001"   # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - /mnt/hdd-storage/PPPK/minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - pipeline-network


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: pppk-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - /mnt/hdd-storage/PPPK/zookeeper_data:/var/lib/zookeeper/data
      - /mnt/hdd-storage/PPPK/zookeeper_log:/var/lib/zookeeper/log
    networks:
      - pipeline-network


  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: pppk-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://10.0.0.42:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /mnt/hdd-storage/PPPK/kafka_data:/var/lib/kafka/data
    networks:
      - pipeline-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: pppk-kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - pipeline-network

networks:
  pipeline-network:
    driver: bridge
